const actionTypes = {
    GET_INPUT: 'GET_INPUT',
    REGISTER_WITH_EMAIL: 'REGISTER_WITH_EMAIL',
    REGISTER_WITH_GOOGLE: 'REGISTER_WITH_GOOGLE',
    REGISTRATION_ERROR: 'REGISTRATION_ERROR',
    REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
};

export default actionTypes;
