export const actionTypes = {
    INPUT_LISTEN: 'INPUT_LISTEN',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REMEMBER_USER: 'REMEMBER_USER',
    VERIFY_REQUEST: 'VERIFY_REQUEST',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
};
