language: node_js
node_js:
  - "node"

script:
  - npm run lint
  - npm test
  - npm run build
after_success:
  - firebase use --token 'cleanit-7147d'
  - firebase --non-interactive --token 'AIzaSyA4e8s9kuZvJBMAJVX4VUdxABoVwqwAu8A'
