export const actionTypes = {
    INPUT_LISTEN: 'INPUT_LISTEN',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    VERIFY_REQUEST: 'VERIFY_REQUEST',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
};
