export const actionTypes = {
    INPUT_LISTEN: 'INPUT_LISTEN',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    VERIFY_REQUEST: 'VERIFY_REQUEST',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
};
