const actionTypes = {
    LISTEN_FOR_INPUT: 'LISTEN_FOR_INPUT',
    REMEMBER_ME: 'REMEMBER_ME',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    SIGNIN_REQUEST: 'SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    VERIFICATION_REQUEST: 'VERIFICATION_REQUEST',
    VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
};

export default actionTypes;
