export const actionTypes = {
    LISTEN_FOR_INPUT: 'LISTEN_FOR_INPUT',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    SIGNIN_REQUEST: 'SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    VERIFICATION_REQUEST: 'VERIFICATION_REQUEST',
    VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
};
